// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  art: dynamic(() => import("./Art")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  logo: dynamic(() => import("./Logo")),
  work: dynamic(() => import("./Work")),
};
